# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da4fce4c5e7b90522e1660e04e1a123af853253b08a5fcc5520c0b29de2149c8b9464156062f3685d6774e558955fe49503a33711a7c42ddcc1a3278afc9e2b

test:
  secret_key_base: a27992dc1c376d9936dc2efc34ee14c3b97b80479c392c1a3e4155a780556d01b05e00ca19dc6093719b0ec925b587506c60c6e80a7d7b91493913882175aa29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
